FIX: Ajustes no jacoco

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -33,8 +33,11 @@ jobs:
       - name: Grant execute permission for Gradlew
         run: chmod +x gradlew
 
-      - name: Build and run tests
-        run: ./gradlew clean test jacocoTestReport
+      - name: List JaCoCo data files (debug step)
+        run: ls -la build/jacoco/test.exec || echo "JaCoCo data file not found"
+
+      - name: Clean and run tests
+        run: ./gradlew clean test jacocoTestReport --info
 
       - name: Upload coverage report
         uses: actions/upload-artifact@v3
